#!/usr/bin/env sh
#  ╔═╗═╗ ╦╦ ╦╦╔═╔╦╗╦═╗╔═╗  - z0mbi3
#  ╚═╗╔╩╦╝╠═╣╠╩╗ ║║╠╦╝║    - https://github.com/gh0stzk/dotfiles
#  ╚═╝╩ ╚═╩ ╩╩ ╩═╩╝╩╚═╚═╝  - z0mbi3.zk@protonmail.com
#			z0mbi3 config..

# Show keybindings help
alt + F1
	KeybindingsHelp
	
# Open Terminal (alacritty)
super + Return
	OpenApps --terminal
	
# Open floating Terminal
super + alt + Return
	OpenApps --floating

# Menu aplicaciones
super + @space
	OpenApps --menu

#打开项目选择
super + alt + @space
    ~/Documents/startProject.py

# 顶部固定终端
super + alt + o
	tdrop -a -w 70% -h 35% -y 0 -x 15%  --class scratch alacritty --class=scratch

# Power off, Reboot, Log out, Lockscreen, kill an app
ctrl + super + alt + {p,r,q,l,k}
	{systemctl poweroff, systemctl reboot,bspc quit,physlock -d,xkill}

# Apps
shift + alt + {m,b,e,t,c,j,2}
	OpenApps --{music,browser,files,txt,code,jo,mail}

# Hide/Show Bar (Polybar and/or eww)
super + {h,u}
	HideBar {-h,-u}

# Change transparency on focused window
ctrl + alt {plus,minus,t}
	{picom-trans -c -o +3, picom-trans -c -o -1, picom-trans -c -d}

# 屏幕截图
Print
	flameshot screen

# 等待10s选择截图
ctrl + Print
	SleepDunst 10 && flameshot gui

# 等待10s屏幕截图
alt + Print
	SleepDunst 10 && flameshot screen

# 选择截图
ctrl + alt + a
    flameshot gui

# Reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd; dunstify -u low -i ~/.config/bspwm/assets/reload.svg 'sxhkd' 'The configuration file has been reloaded successfully!'

# Random wallpaper
super + alt + w
	feh -z --no-fehbg --bg-fill "$HOME"/Pictures/wallpaper
#
# bspwm hotkeys
#

# Reload BSPWM
super + alt + r
	bspc wm -r

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

####

# rotate desktop
super + r
	bspc node @/ --rotate {90,-90}

# Circulate the leaves of the tree
super + c
	bspc node @/ --circulate {backward,forward}

# Make split ratios equal
super + equal
	bspc node @/ --equalize

# Make split ratios balanced
super + minus
	bspc node @/ --balance

# alternate between the tiled and monocle layout
# 当前窗口最大化
super + m
	bspc desktop -l next

# swap the current node and the biggest node
# 交换当前节点和最大节点
super + g
	bspc node -s biggest

# set the window state
# 平铺、伪平铺、浮动、全屏
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
# 标记、锁定、粘性、私有、隐藏
ctrl + alt {m,x,s,p,z}
	bspc node -g {marked,locked,sticky,private,hidden}

ctrl + alt + shift + z
    bspc node {,$(bspc query -N -n .hidden | tail -n1)} -g hidden=off

# hide/unhide all windows
super + d
    bspc query -N -n .local.window | xargs -I ID bspc node ID -g hidden


# Focused desktop window gaps scroll
#super + button{4,5}
#	bspc config -d focused window_gap $((`bspc config -d focused window_gap` {-,+} 5 ))

# Global window gaps scroll
#super + alt + button{4,5}
#	bspc config window_gap $(( $(bspc config window_gap) {-,+} 5 ))

# focus the node in the given direction
# 切换焦点
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
#alt + {_,shift + }Tab
#	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + alt + {Left,Right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel


# focus a floating window from a tiled window
super + a
    if [ "$(bspc query -N -n focused.floating)" ]; then \
        bspc node -f last.tiled.local; \
    else \
        bspc node -f last.floating.local; \
    fi


#
# move/resize
#

# 向外膨胀
super + alt + {h,j,k,l}
	bspc node -z {left -10 0,bottom 0 10,top 0 -10,right 10 0}

# 向内收缩
super + alt + shift + {h,j,k,l}
	bspc node -z {right -10 0,top 0 10,bottom 0 -10,left 10 0}

# move a floating window
alt + shift + {Left,Down,Up,Right}
	bspc node -v {-10 0,0 10,0 -10,10 0}

# 播放暂停
ctrl + alt + {space,Left,Right,Up,Down} 
    mpc {toggle,prev,next,volume +5,volume -5}

super + alt {Up,Down}
  dunstify -u low -r 114514 '亮度调节' `Ld {+,-}` 
# Manage brightness
XF86MonBrightness{Up,Down}
    sh Brightness {up,down}

# Volume control
#XF86Audio{RaiseVolume,LowerVolume,Mute}
#	Volume{ --inc, --dec, --toggle}

# volume
XF86Audio{LowerVolume,RaiseVolume,Mute}
    ~/.config/scripts/volume_dunst {down,up,mute}

# Music Control
XF86Audio{Next,Prev,Play,Stop}
	MediaControl {--next,--previous,--toggle,--stop}
