#!/bin/sh

mem="$(free -m | grep --extended-regexp 'Mem|内存：')"

total="$(echo $mem | awk '{ print $2 }')"
used="$(echo $mem | awk '{ print $3 }')"

free=$(expr $total - $used)

if [ "$1" = "total" ]; then
    echo $total
elif [ "$1" = "used" ]; then
    echo $used
elif [ "$1" = "free" ]; then
    echo $free
elif [ "$1" = "progress" ]; then
    printf "%.0f\n" $(echo $mem | awk '{print ($3/$2)*100}')
fi
