# Some default env vars.

env = XCURSOR_SIZE,24
env = LANG, zh_CN.UTF-8
env = XMODIFIERS, @im=fcitx
env = GTK_IM_MODULE, fcitx
env = QT_IM_MODULE, fcitx
env = SDL_IM_MODULE, fcitx
env = QT_QPA_PLATFORMTHEME, qt5ct
env = WLR_NO_HARDWARE_CURSORS, 1
env = GLFW_IM_MODULE, ibus
env = GDK_SYNCHRONIZE, 1
env = GDK_SYNCHRONIZE, 1