[default_view]

keymap = [
	{ keys = [ "escape" ],		commands = ["escape"] },
	{ keys = ["ctrl+t"], commands = ["new_tab"] },
  { keys = ["alt+t"], commands = ["new_tab --cursor"] },
  { keys = ["T"], commands = ["new_tab --current"] },
  { keys = ["W"], commands = ["close_tab"] },
  { keys = ["ctrl+w"], commands = ["close_tab"] },
  { keys = ["q"], commands = ["close_tab"] },
  { keys = ["ctrl+c"], commands = ["quit --output-current-directory"] },
  { keys = ["Q"], commands = ["quit"] },

	{ keys = [ "R" ],		commands = ["reload_dirlist"] },
	{ keys = [ "z", "h" ],		commands = ["toggle_hidden"] },
	{ keys = [ "ctrl+h" ],		commands = ["toggle_hidden"] },
	{ keys = [ "t", "i" ],		commands = ["tab_switch 1"] },
	{ keys = [ "t", "n" ],		commands = ["tab_switch -1"] },

	{ keys = [ "alt+1" ],		commands = ["tab_switch_index 1"] },
	{ keys = [ "alt+2" ],		commands = ["tab_switch_index 2"] },
	{ keys = [ "alt+3" ],		commands = ["tab_switch_index 3"] },
	{ keys = [ "alt+4" ],		commands = ["tab_switch_index 4"] },
	{ keys = [ "alt+5" ],		commands = ["tab_switch_index 5"] },

	{ keys = [ "1" ],		commands = ["numbered_command 1"] },
	{ keys = [ "2" ],		commands = ["numbered_command 2"] },
	{ keys = [ "3" ],		commands = ["numbered_command 3"] },
	{ keys = [ "4" ],		commands = ["numbered_command 4"] },
	{ keys = [ "5" ],		commands = ["numbered_command 5"] },
	{ keys = [ "6" ],		commands = ["numbered_command 6"] },
	{ keys = [ "7" ],		commands = ["numbered_command 7"] },
	{ keys = [ "8" ],		commands = ["numbered_command 8"] },
	{ keys = [ "9" ],		commands = ["numbered_command 9"] },

	# arrow keys
	{ keys = [ "arrow_up" ],	commands = ["cursor_move_up"] },
	{ keys = [ "arrow_down" ],	commands = ["cursor_move_down"] },
	{ keys = [ "arrow_left" ],	commands = ["cd .."] },
	{ keys = [ "arrow_right" ],	commands = ["open"] },
	{ keys = [ "\n" ],		commands = ["open"] },
	{ keys = [ "home" ],		commands = ["cursor_move_home"] },
	#{ keys = [ "end" ],		commands = ["cursor_move_end"] },
	#{ keys = [ "page_up" ],		commands = ["cursor_move_page_up"] },
	#{ keys = [ "page_down" ],	commands = ["cursor_move_page_down"] },
	{ keys = [ "page_up" ],  	commands = ["cursor_move_page_up 0.5"] },
	{ keys = [ "page_down" ], 		commands = ["cursor_move_page_down 0.5"] },

	# vim-like keybindings
	{ keys = [ "j" ],		commands = ["cursor_move_down"] },
	{ keys = [ "k" ],		commands = ["cursor_move_up"] },
	{ keys = [ "J" ],		commands = ["cursor_move_down 5"] },
	{ keys = [ "K" ],		commands = ["cursor_move_up 5"] },
	{ keys = [ "h" ],		commands = ["cd .."] },
	{ keys = [ "b" ],		commands = ["cd -"] },
	{ keys = [ "l" ],		commands = ["open"] },
	{ keys = [ "g", "g" ],		commands = ["cursor_move_home"] },
	{ keys = [ "G" ],		commands = ["cursor_move_end"] },
	{ keys = [ "r" ],		commands = ["open_with"] },

	# { keys = [ "H" ],		commands = ["cursor_move_page_home"] },
	# { keys = [ "L" ],		commands = ["cursor_move_page_middle"] },
	# { keys = [ "M" ],		commands = ["cursor_move_page_end"] },

	{ keys = [ "[" ],		commands = ["parent_cursor_move_up"] },
	{ keys = [ "]" ],		commands = ["parent_cursor_move_down"] },

	{ keys = [ "c", "d" ],		commands = [":cd "] },
	{ keys = [ "d", "d" ],		commands = ["cut_files"] },
	{ keys = [ "y", "y" ],		commands = ["copy_files"] },
	{ keys = [ "y", "n" ],		commands = ["copy_filename"] },
	{ keys = [ "y", "." ],		commands = ["copy_filename_without_extension"] },
	{ keys = [ "y", "p" ],		commands = ["copy_filepath"] },
	{ keys = [ "y", "d" ],		commands = ["copy_dirpath"] },

	{ keys = [ "p", "l" ],		commands = ["symlink_files --relative=false"] },
	{ keys = [ "p", "L" ],		commands = ["symlink_files --relative=true"] },

	{ keys = [ "delete" ],		commands = ["delete_files"] },
	{ keys = [ "d", "D" ],		commands = ["delete_files"] },

	{ keys = [ "p", "p" ],		commands = ["paste_files"] },
	{ keys = [ "p", "o" ],		commands = ["paste_files --overwrite=true"] },

	#{ keys = [ "a" ],		commands = ["rename_append"] },
	#{ keys = [ "k" ],		commands = ["rename_prepend"] },

	#{ keys = [ "T" ],		commands = [":touch "] },

	{ keys = [ " " ],		commands = ["select --toggle=true"] },
	{ keys = [ "v" ],		commands = ["select --all=true --toggle=true"] },
	{ keys = [ "V" ],		commands = ["toggle_visual"] },

	{ keys = [ "w" ],		commands = ["show_tasks --exit-key=w"] },
	{ keys = [ "c", "b" ],		commands = ["bulk_rename"] },
	{ keys = [ "c", "m" ],		commands = ["set_mode"] },
	{ keys = [ "c", "w" ],		commands = ["rename_keep_ext"] },
	{ keys = [ "c", "n" ],		commands = [":rename "] },

	{ keys = [ ":" ],		commands = [":"] },
	{ keys = [ ";" ],		commands = [":"] },

	{ keys = [ "'" ],		commands = [":shell "] },
	{ keys = [ "S" ],		commands = ["shell zsh"] },
	{ keys = [ "ctrl+g" ],		commands = ["shell lazygit"] },
	{ keys = [ "M" ],		commands = [":mkdir "] },

	{ keys = [ "/" ],		commands = [":search_inc "] },
	{ keys = [ "f" ],		commands = [":filter  "] },
	# { keys = [ "/" ],		commands = [":search "] },
	# { keys = [ "|" ],		commands = [":search_inc "] },
	{ keys = [ "\\" ],		commands = [":search_glob "] },
	# { keys = [ "ctrl+f" ],		commands = ["search_fzf"] },
	{ keys = [ "ctrl+f" ],		commands = ["subdir_fzf"] },
	{ keys = [ "ctrl+p" ],		commands = ["subdir_fzf"] },

	{ keys = [ "=" ],		commands = ["search_next"] },
	{ keys = [ "-" ],		commands = ["search_prev"] },

	{ keys = [ "o", "r" ],		commands = ["sort reverse"] },
	{ keys = [ "o", "l" ],		commands = ["sort lexical"] },
	{ keys = [ "o", "m" ],		commands = ["sort mtime"] },
	{ keys = [ "o", "c" ],		commands = ["sort mtime"] },
	{ keys = [ "o", "n" ],		commands = ["sort natural"] },
	{ keys = [ "o", "s" ],		commands = ["sort size"] },
	{ keys = [ "o", "e" ],		commands = ["sort ext"] },

	{ keys = [ "m", "s" ],		commands = ["linemode size"] },
	{ keys = [ "m", "m" ],		commands = ["linemode mtime"] },
	#{ keys = [ "m", "M" ],		commands = ["linemode sizemtime"] },

	{ keys = [ "g", "r" ],		commands = ["cd /"] },
	{ keys = [ "g", "d" ],		commands = ["cd ~/Downloads"] },
	{ keys = [ "g", "e" ],		commands = ["cd /etc"] },
	{ keys = [ "g", "h" ],		commands = ["cd ~/"] },
	{ keys = [ "g", "i" ],		commands = ["cd ~/Ocyss"] },
	{ keys = [ "g", "l" ],		commands = ["cd /lib"] },
	{ keys = [ "g", "p", "g" ],		commands = ["cd ~/Documents/go/src"] },
	{ keys = [ "g", "f", "f" ],		commands = ["cd ~/dotfiles"] },
	{ keys = [ "g", "f", "b" ],		commands = ["cd ~/dotfiles/bspwm"] },
	{ keys = [ "g", "f", "h" ],		commands = ["cd ~/dotfiles/hypr"] },
	{ keys = [ "g", "f", "s" ],		commands = ["cd ~/dotfiles/sxhkd"] },
	{ keys = [ "g", "f", "j" ],		commands = ["cd ~/dotfiles/joshuto"] },
	{ keys = [ "g", "f", "n" ],		commands = ["cd ~/dotfiles/npc"] },
	{ keys = [ "g", "f", "p" ],		commands = ["cd ~/dotfiles/picom"] },
	{ keys = [ "g", "f", "e" ],		commands = ["cd ~/dotfiles/eww"] },
	{ keys = [ "?" ],		commands = ["help"] }
]

[task_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	commands = ["cursor_move_up"] },
	{ keys = [ "arrow_down" ],	commands = ["cursor_move_down"] },
	{ keys = [ "home" ],		commands = ["cursor_move_home"] },
	{ keys = [ "end" ],		commands = ["cursor_move_end"] },

	# vim-like keybindings
	{ keys = [ "e" ],		commands = ["cursor_move_down"] },
	{ keys = [ "u" ],		commands = ["cursor_move_up"] },
	{ keys = [ "g", "g" ],		commands = ["cursor_move_home"] },
	{ keys = [ "G" ],		commands = ["cursor_move_end"] },

	{ keys = [ "w" ],		commands = ["show_tasks"] },
	{ keys = [ "escape" ],		commands = ["show_tasks"] },
]

[help_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	commands = ["cursor_move_up"] },
	{ keys = [ "arrow_down" ],	commands = ["cursor_move_down"] },
	{ keys = [ "home" ],		commands = ["cursor_move_home"] },
	{ keys = [ "end" ],		commands = ["cursor_move_end"] },

	# vim-like keybindings
	{ keys = [ "e" ],		commands = ["cursor_move_down"] },
	{ keys = [ "u" ],		commands = ["cursor_move_up"] },
	{ keys = [ "E" ],		commands = ["cursor_move_down 5"] },
	{ keys = [ "U" ],		commands = ["cursor_move_up 5"] },
	{ keys = [ "g", "g" ],		commands = ["cursor_move_home"] },
	{ keys = [ "G" ],		commands = ["cursor_move_end"] },

	{ keys = [ "w" ],		commands = ["show_tasks"] },
	{ keys = [ "escape" ],		commands = ["show_tasks"] },
	{ keys = [ "q" ],		commands = ["show_tasks"] },
]
